### PR TITLE
Allow HTML in tooltip

### PR DESCRIPTION
**Pull request by HitkoDev**

### CODE REVIEW

**Comment by chrisdavies** [comment]
Hm. I'm a little hesitant about this, though it's probably just fine. I wonder if there should be a way to specify "I want my tooltip content escaped vs raw HTML"?

**Comment by LasseRafn** [comment]
👍

I can't find a scenario where it would break anything. Though I understand why you'd want to be able to specify if you'd like it escaped or not.

Alternatively, people should escape their HTML prior to passing it to the attribute.

**Comment by chrisdavies** [comment]
I think that's generally true, yeah. Leaving the escaping of things to the view layer rather than this library is probably the correct approach. I'll update the readme and get this out on npm later today.

**Comment by LasseRafn** [comment]
Sounds great, yeah exactly. Thanks! Good job. +1

**Pull request merged**
